import type { Metadata } from "next";
import "./globals.css";
import { montserrat_font } from "@/Fonts";
import { Providers } from "@/components/Auth/Providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${montserrat_font.className} antialiased bg-[#eef0f2] text-black`}
        >
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
  );
}
