import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import { montserrat_font } from "./page";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat_font.className} antialiased bg-[#eef0f2] text-black`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
