import { montserrat_font } from "@/Fonts"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat_font.className}`}>
        {children}
      </body>
    </html>
  )
}
